[2023-08-30T23:23:45.483+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-29T23:23:40.156765+00:00/task_id=second_group.inner_function1 permission to 509
[2023-08-30T23:23:45.484+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-29T23:23:40.156765+00:00/task_id=second_group.inner_function1 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-29T23:23:40.156765+00:00/task_id=second_group.inner_function1'
[2023-08-30T23:23:45.528+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-29T23:23:40.156765+00:00/task_id=second_group.inner_function1 permission to 509
[2023-08-30T23:23:45.528+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-29T23:23:40.156765+00:00/task_id=second_group.inner_function1 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-29T23:23:40.156765+00:00/task_id=second_group.inner_function1'
[2023-08-30T23:23:45.664+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_python_with_task_group.second_group.inner_function1 scheduled__2023-08-29T23:23:40.156765+00:00 [queued]>
[2023-08-30T23:23:45.673+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_python_with_task_group.second_group.inner_function1 scheduled__2023-08-29T23:23:40.156765+00:00 [queued]>
[2023-08-30T23:23:45.673+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-30T23:23:45.707+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): second_group.inner_function1> on 2023-08-29 23:23:40.156765+00:00
[2023-08-30T23:23:45.712+0000] {standard_task_runner.py:57} INFO - Started process 2857 to run task
[2023-08-30T23:23:45.714+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_python_with_task_group', 'second_group.inner_function1', 'scheduled__2023-08-29T23:23:40.156765+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/dags_python_with_task_group.py', '--cfg-path', '/tmp/tmp_cvlnkdt']
[2023-08-30T23:23:45.717+0000] {standard_task_runner.py:85} INFO - Job 196: Subtask second_group.inner_function1
[2023-08-30T23:23:45.775+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-29T23:23:40.156765+00:00/task_id=second_group.inner_function1 permission to 509
[2023-08-30T23:23:45.775+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-29T23:23:40.156765+00:00/task_id=second_group.inner_function1 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-29T23:23:40.156765+00:00/task_id=second_group.inner_function1'
[2023-08-30T23:23:45.778+0000] {task_command.py:410} INFO - Running <TaskInstance: dags_python_with_task_group.second_group.inner_function1 scheduled__2023-08-29T23:23:40.156765+00:00 [running]> on host 07fcf706bef2
[2023-08-30T23:23:45.902+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dags_python_with_task_group' AIRFLOW_CTX_TASK_ID='second_group.inner_function1' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T23:23:40.156765+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-29T23:23:40.156765+00:00'
[2023-08-30T23:23:45.904+0000] {logging_mixin.py:150} INFO - 두 번째 TaskGroup 내 첫 번째 task입니다.
[2023-08-30T23:23:45.905+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-08-30T23:23:45.916+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=dags_python_with_task_group, task_id=second_group.inner_function1, execution_date=20230829T232340, start_date=20230830T232345, end_date=20230830T232345
[2023-08-30T23:23:45.967+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-30T23:23:45.990+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
