[2023-09-30T07:47:58.817+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-30T23:23:40.156765+00:00/task_id=first_group.inner_function2 permission to 509
[2023-09-30T07:47:58.820+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-30T23:23:40.156765+00:00/task_id=first_group.inner_function2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-30T23:23:40.156765+00:00/task_id=first_group.inner_function2'
[2023-09-30T07:47:58.939+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-30T23:23:40.156765+00:00/task_id=first_group.inner_function2 permission to 509
[2023-09-30T07:47:58.943+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-30T23:23:40.156765+00:00/task_id=first_group.inner_function2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-30T23:23:40.156765+00:00/task_id=first_group.inner_function2'
[2023-09-30T07:47:59.378+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_python_with_task_group.first_group.inner_function2 scheduled__2023-08-30T23:23:40.156765+00:00 [queued]>
[2023-09-30T07:47:59.410+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_python_with_task_group.first_group.inner_function2 scheduled__2023-08-30T23:23:40.156765+00:00 [queued]>
[2023-09-30T07:47:59.411+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-09-30T07:47:59.485+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): first_group.inner_function2> on 2023-08-30 23:23:40.156765+00:00
[2023-09-30T07:47:59.497+0000] {standard_task_runner.py:57} INFO - Started process 199 to run task
[2023-09-30T07:47:59.504+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_python_with_task_group', 'first_group.inner_function2', 'scheduled__2023-08-30T23:23:40.156765+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/dags_python_with_task_group.py', '--cfg-path', '/tmp/tmpzxxex2a9']
[2023-09-30T07:47:59.509+0000] {standard_task_runner.py:85} INFO - Job 269: Subtask first_group.inner_function2
[2023-09-30T07:47:59.667+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-30T23:23:40.156765+00:00/task_id=first_group.inner_function2 permission to 509
[2023-09-30T07:47:59.669+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-30T23:23:40.156765+00:00/task_id=first_group.inner_function2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-30T23:23:40.156765+00:00/task_id=first_group.inner_function2'
[2023-09-30T07:47:59.676+0000] {task_command.py:410} INFO - Running <TaskInstance: dags_python_with_task_group.first_group.inner_function2 scheduled__2023-08-30T23:23:40.156765+00:00 [running]> on host 07fcf706bef2
[2023-09-30T07:47:59.927+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dags_python_with_task_group' AIRFLOW_CTX_TASK_ID='first_group.inner_function2' AIRFLOW_CTX_EXECUTION_DATE='2023-08-30T23:23:40.156765+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-30T23:23:40.156765+00:00'
[2023-09-30T07:47:59.930+0000] {logging_mixin.py:150} INFO - 첫 번째 TaskGroup내 두 번째 task입니다.
[2023-09-30T07:47:59.931+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-09-30T07:47:59.949+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=dags_python_with_task_group, task_id=first_group.inner_function2, execution_date=20230830T232340, start_date=20230930T074759, end_date=20230930T074759
[2023-09-30T07:48:00.081+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-09-30T07:48:00.257+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
