[2023-08-30T23:23:48.008+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-29T23:23:40.156765+00:00/task_id=second_group.inner_function2 permission to 509
[2023-08-30T23:23:48.009+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-29T23:23:40.156765+00:00/task_id=second_group.inner_function2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-29T23:23:40.156765+00:00/task_id=second_group.inner_function2'
[2023-08-30T23:23:48.056+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-29T23:23:40.156765+00:00/task_id=second_group.inner_function2 permission to 509
[2023-08-30T23:23:48.057+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-29T23:23:40.156765+00:00/task_id=second_group.inner_function2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-29T23:23:40.156765+00:00/task_id=second_group.inner_function2'
[2023-08-30T23:23:48.195+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_python_with_task_group.second_group.inner_function2 scheduled__2023-08-29T23:23:40.156765+00:00 [queued]>
[2023-08-30T23:23:48.207+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_python_with_task_group.second_group.inner_function2 scheduled__2023-08-29T23:23:40.156765+00:00 [queued]>
[2023-08-30T23:23:48.208+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-30T23:23:48.243+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): second_group.inner_function2> on 2023-08-29 23:23:40.156765+00:00
[2023-08-30T23:23:48.247+0000] {standard_task_runner.py:57} INFO - Started process 2860 to run task
[2023-08-30T23:23:48.252+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_python_with_task_group', 'second_group.inner_function2', 'scheduled__2023-08-29T23:23:40.156765+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/dags_python_with_task_group.py', '--cfg-path', '/tmp/tmpvhrt4rs7']
[2023-08-30T23:23:48.255+0000] {standard_task_runner.py:85} INFO - Job 197: Subtask second_group.inner_function2
[2023-08-30T23:23:48.323+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-29T23:23:40.156765+00:00/task_id=second_group.inner_function2 permission to 509
[2023-08-30T23:23:48.324+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-29T23:23:40.156765+00:00/task_id=second_group.inner_function2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_with_task_group/run_id=scheduled__2023-08-29T23:23:40.156765+00:00/task_id=second_group.inner_function2'
[2023-08-30T23:23:48.327+0000] {task_command.py:410} INFO - Running <TaskInstance: dags_python_with_task_group.second_group.inner_function2 scheduled__2023-08-29T23:23:40.156765+00:00 [running]> on host 07fcf706bef2
[2023-08-30T23:23:48.475+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dags_python_with_task_group' AIRFLOW_CTX_TASK_ID='second_group.inner_function2' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T23:23:40.156765+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-29T23:23:40.156765+00:00'
[2023-08-30T23:23:48.477+0000] {logging_mixin.py:150} INFO - 두 번째 TaskGroup내 두 번째 task입니다.
[2023-08-30T23:23:48.477+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-08-30T23:23:48.487+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=dags_python_with_task_group, task_id=second_group.inner_function2, execution_date=20230829T232340, start_date=20230830T232348, end_date=20230830T232348
[2023-08-30T23:23:48.543+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-30T23:23:48.561+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
