[2023-08-30T20:45:45.999+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-29T00:10:00+00:00/task_id=bash_push permission to 509
[2023-08-30T20:45:46.002+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-29T00:10:00+00:00/task_id=bash_push permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-29T00:10:00+00:00/task_id=bash_push'
[2023-08-30T20:45:46.134+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-29T00:10:00+00:00/task_id=bash_push permission to 509
[2023-08-30T20:45:46.135+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-29T00:10:00+00:00/task_id=bash_push permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-29T00:10:00+00:00/task_id=bash_push'
[2023-08-30T20:45:46.485+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_bash_with_xcom.bash_push scheduled__2023-08-29T00:10:00+00:00 [queued]>
[2023-08-30T20:45:46.499+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_bash_with_xcom.bash_push scheduled__2023-08-29T00:10:00+00:00 [queued]>
[2023-08-30T20:45:46.499+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-30T20:45:46.549+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): bash_push> on 2023-08-29 00:10:00+00:00
[2023-08-30T20:45:46.556+0000] {standard_task_runner.py:57} INFO - Started process 81 to run task
[2023-08-30T20:45:46.562+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_bash_with_xcom', 'bash_push', 'scheduled__2023-08-29T00:10:00+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/dags_bash_with_xcom.py', '--cfg-path', '/tmp/tmpr_g3irs0']
[2023-08-30T20:45:46.565+0000] {standard_task_runner.py:85} INFO - Job 185: Subtask bash_push
[2023-08-30T20:45:46.651+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-29T00:10:00+00:00/task_id=bash_push permission to 509
[2023-08-30T20:45:46.652+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-29T00:10:00+00:00/task_id=bash_push permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-29T00:10:00+00:00/task_id=bash_push'
[2023-08-30T20:45:46.656+0000] {task_command.py:410} INFO - Running <TaskInstance: dags_bash_with_xcom.bash_push scheduled__2023-08-29T00:10:00+00:00 [running]> on host 07fcf706bef2
[2023-08-30T20:45:46.839+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dags_bash_with_xcom' AIRFLOW_CTX_TASK_ID='bash_push' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T00:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-29T00:10:00+00:00'
[2023-08-30T20:45:46.841+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-30T20:45:46.842+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo START && echo XCOM_PUSHEDNone && echo COMPLETE']
[2023-08-30T20:45:46.853+0000] {subprocess.py:86} INFO - Output:
[2023-08-30T20:45:46.854+0000] {subprocess.py:93} INFO - START
[2023-08-30T20:45:46.855+0000] {subprocess.py:93} INFO - XCOM_PUSHEDNone
[2023-08-30T20:45:46.856+0000] {subprocess.py:93} INFO - COMPLETE
[2023-08-30T20:45:46.856+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-30T20:45:46.933+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=dags_bash_with_xcom, task_id=bash_push, execution_date=20230829T001000, start_date=20230830T204546, end_date=20230830T204546
[2023-08-30T20:45:47.056+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-30T20:45:47.083+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
