[2023-08-29T23:24:08.708+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_with_task_group/run_id=manual__2023-08-29T23:24:04.299332+00:00/task_id=first_group.inner_function2 permission to 509
[2023-08-29T23:24:08.709+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_with_task_group/run_id=manual__2023-08-29T23:24:04.299332+00:00/task_id=first_group.inner_function2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_with_task_group/run_id=manual__2023-08-29T23:24:04.299332+00:00/task_id=first_group.inner_function2'
[2023-08-29T23:24:08.758+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_with_task_group/run_id=manual__2023-08-29T23:24:04.299332+00:00/task_id=first_group.inner_function2 permission to 509
[2023-08-29T23:24:08.759+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_with_task_group/run_id=manual__2023-08-29T23:24:04.299332+00:00/task_id=first_group.inner_function2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_with_task_group/run_id=manual__2023-08-29T23:24:04.299332+00:00/task_id=first_group.inner_function2'
[2023-08-29T23:24:08.939+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_python_with_task_group.first_group.inner_function2 manual__2023-08-29T23:24:04.299332+00:00 [queued]>
[2023-08-29T23:24:08.948+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_python_with_task_group.first_group.inner_function2 manual__2023-08-29T23:24:04.299332+00:00 [queued]>
[2023-08-29T23:24:08.949+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-29T23:24:08.983+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): first_group.inner_function2> on 2023-08-29 23:24:04.299332+00:00
[2023-08-29T23:24:08.987+0000] {standard_task_runner.py:57} INFO - Started process 177 to run task
[2023-08-29T23:24:08.992+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_python_with_task_group', 'first_group.inner_function2', 'manual__2023-08-29T23:24:04.299332+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/dags_python_with_task_group.py', '--cfg-path', '/tmp/tmpiop13qcb']
[2023-08-29T23:24:08.995+0000] {standard_task_runner.py:85} INFO - Job 172: Subtask first_group.inner_function2
[2023-08-29T23:24:09.083+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_with_task_group/run_id=manual__2023-08-29T23:24:04.299332+00:00/task_id=first_group.inner_function2 permission to 509
[2023-08-29T23:24:09.084+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_with_task_group/run_id=manual__2023-08-29T23:24:04.299332+00:00/task_id=first_group.inner_function2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_with_task_group/run_id=manual__2023-08-29T23:24:04.299332+00:00/task_id=first_group.inner_function2'
[2023-08-29T23:24:09.087+0000] {task_command.py:410} INFO - Running <TaskInstance: dags_python_with_task_group.first_group.inner_function2 manual__2023-08-29T23:24:04.299332+00:00 [running]> on host 07fcf706bef2
[2023-08-29T23:24:09.207+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dags_python_with_task_group' AIRFLOW_CTX_TASK_ID='first_group.inner_function2' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T23:24:04.299332+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-29T23:24:04.299332+00:00'
[2023-08-29T23:24:09.209+0000] {logging_mixin.py:150} INFO - 첫 번째 TaskGroup내 두 번째 task입니다.
[2023-08-29T23:24:09.210+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-08-29T23:24:09.220+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=dags_python_with_task_group, task_id=first_group.inner_function2, execution_date=20230829T232404, start_date=20230829T232408, end_date=20230829T232409
[2023-08-29T23:24:09.284+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-29T23:24:09.323+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
