[2023-08-31T02:25:59.304+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-30T00:10:00+00:00/task_id=bash_push permission to 509
[2023-08-31T02:25:59.305+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-30T00:10:00+00:00/task_id=bash_push permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-30T00:10:00+00:00/task_id=bash_push'
[2023-08-31T02:25:59.353+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-30T00:10:00+00:00/task_id=bash_push permission to 509
[2023-08-31T02:25:59.354+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-30T00:10:00+00:00/task_id=bash_push permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-30T00:10:00+00:00/task_id=bash_push'
[2023-08-31T02:25:59.534+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_bash_with_xcom.bash_push scheduled__2023-08-30T00:10:00+00:00 [queued]>
[2023-08-31T02:25:59.545+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_bash_with_xcom.bash_push scheduled__2023-08-30T00:10:00+00:00 [queued]>
[2023-08-31T02:25:59.545+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-31T02:25:59.605+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): bash_push> on 2023-08-30 00:10:00+00:00
[2023-08-31T02:25:59.611+0000] {standard_task_runner.py:57} INFO - Started process 65 to run task
[2023-08-31T02:25:59.615+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_bash_with_xcom', 'bash_push', 'scheduled__2023-08-30T00:10:00+00:00', '--job-id', '203', '--raw', '--subdir', 'DAGS_FOLDER/dags_bash_with_xcom.py', '--cfg-path', '/tmp/tmpuwk8f9lj']
[2023-08-31T02:25:59.618+0000] {standard_task_runner.py:85} INFO - Job 203: Subtask bash_push
[2023-08-31T02:25:59.788+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-30T00:10:00+00:00/task_id=bash_push permission to 509
[2023-08-31T02:25:59.789+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-30T00:10:00+00:00/task_id=bash_push permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-30T00:10:00+00:00/task_id=bash_push'
[2023-08-31T02:25:59.792+0000] {task_command.py:410} INFO - Running <TaskInstance: dags_bash_with_xcom.bash_push scheduled__2023-08-30T00:10:00+00:00 [running]> on host 07fcf706bef2
[2023-08-31T02:26:00.015+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dags_bash_with_xcom' AIRFLOW_CTX_TASK_ID='bash_push' AIRFLOW_CTX_EXECUTION_DATE='2023-08-30T00:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-30T00:10:00+00:00'
[2023-08-31T02:26:00.017+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-31T02:26:00.019+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo START && echo XCOM_PUSHEDNone && echo COMPLETE']
[2023-08-31T02:26:00.030+0000] {subprocess.py:86} INFO - Output:
[2023-08-31T02:26:00.031+0000] {subprocess.py:93} INFO - START
[2023-08-31T02:26:00.032+0000] {subprocess.py:93} INFO - XCOM_PUSHEDNone
[2023-08-31T02:26:00.032+0000] {subprocess.py:93} INFO - COMPLETE
[2023-08-31T02:26:00.033+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-31T02:26:00.075+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=dags_bash_with_xcom, task_id=bash_push, execution_date=20230830T001000, start_date=20230831T022559, end_date=20230831T022600
[2023-08-31T02:26:00.188+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-31T02:26:00.211+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
