[2023-08-29T22:12:35.658+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_with_trigger_rule_eg1/run_id=manual__2023-08-29T22:12:33.593926+00:00/task_id=python_upstream_2 permission to 509
[2023-08-29T22:12:35.659+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_with_trigger_rule_eg1/run_id=manual__2023-08-29T22:12:33.593926+00:00/task_id=python_upstream_2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_with_trigger_rule_eg1/run_id=manual__2023-08-29T22:12:33.593926+00:00/task_id=python_upstream_2'
[2023-08-29T22:12:35.709+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_with_trigger_rule_eg1/run_id=manual__2023-08-29T22:12:33.593926+00:00/task_id=python_upstream_2 permission to 509
[2023-08-29T22:12:35.710+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_with_trigger_rule_eg1/run_id=manual__2023-08-29T22:12:33.593926+00:00/task_id=python_upstream_2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_with_trigger_rule_eg1/run_id=manual__2023-08-29T22:12:33.593926+00:00/task_id=python_upstream_2'
[2023-08-29T22:12:35.884+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_python_with_trigger_rule_eg1.python_upstream_2 manual__2023-08-29T22:12:33.593926+00:00 [queued]>
[2023-08-29T22:12:35.895+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_python_with_trigger_rule_eg1.python_upstream_2 manual__2023-08-29T22:12:33.593926+00:00 [queued]>
[2023-08-29T22:12:35.896+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-29T22:12:35.932+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): python_upstream_2> on 2023-08-29 22:12:33.593926+00:00
[2023-08-29T22:12:35.936+0000] {standard_task_runner.py:57} INFO - Started process 2509 to run task
[2023-08-29T22:12:35.940+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_python_with_trigger_rule_eg1', 'python_upstream_2', 'manual__2023-08-29T22:12:33.593926+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/dags_python_with_trigger_rule_eg1.py', '--cfg-path', '/tmp/tmpbdffd8nw']
[2023-08-29T22:12:35.942+0000] {standard_task_runner.py:85} INFO - Job 161: Subtask python_upstream_2
[2023-08-29T22:12:36.025+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_with_trigger_rule_eg1/run_id=manual__2023-08-29T22:12:33.593926+00:00/task_id=python_upstream_2 permission to 509
[2023-08-29T22:12:36.026+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_with_trigger_rule_eg1/run_id=manual__2023-08-29T22:12:33.593926+00:00/task_id=python_upstream_2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_with_trigger_rule_eg1/run_id=manual__2023-08-29T22:12:33.593926+00:00/task_id=python_upstream_2'
[2023-08-29T22:12:36.030+0000] {task_command.py:410} INFO - Running <TaskInstance: dags_python_with_trigger_rule_eg1.python_upstream_2 manual__2023-08-29T22:12:33.593926+00:00 [running]> on host 07fcf706bef2
[2023-08-29T22:12:36.168+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dags_python_with_trigger_rule_eg1' AIRFLOW_CTX_TASK_ID='python_upstream_2' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T22:12:33.593926+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-29T22:12:33.593926+00:00'
[2023-08-29T22:12:36.171+0000] {logging_mixin.py:150} INFO - 정상 처리
[2023-08-29T22:12:36.171+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-08-29T22:12:36.182+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=dags_python_with_trigger_rule_eg1, task_id=python_upstream_2, execution_date=20230829T221233, start_date=20230829T221235, end_date=20230829T221236
[2023-08-29T22:12:36.232+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-29T22:12:36.263+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
