[2023-08-29T19:34:44.025+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_base_branch_operator/run_id=manual__2023-08-29T19:34:41.948544+00:00/task_id=python_branch_task permission to 509
[2023-08-29T19:34:44.027+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_base_branch_operator/run_id=manual__2023-08-29T19:34:41.948544+00:00/task_id=python_branch_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_base_branch_operator/run_id=manual__2023-08-29T19:34:41.948544+00:00/task_id=python_branch_task'
[2023-08-29T19:34:44.070+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_base_branch_operator/run_id=manual__2023-08-29T19:34:41.948544+00:00/task_id=python_branch_task permission to 509
[2023-08-29T19:34:44.071+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_base_branch_operator/run_id=manual__2023-08-29T19:34:41.948544+00:00/task_id=python_branch_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_base_branch_operator/run_id=manual__2023-08-29T19:34:41.948544+00:00/task_id=python_branch_task'
[2023-08-29T19:34:44.231+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_base_branch_operator.python_branch_task manual__2023-08-29T19:34:41.948544+00:00 [queued]>
[2023-08-29T19:34:44.242+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_base_branch_operator.python_branch_task manual__2023-08-29T19:34:41.948544+00:00 [queued]>
[2023-08-29T19:34:44.243+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-29T19:34:44.278+0000] {taskinstance.py:1327} INFO - Executing <Task(CustomBranchOperator): python_branch_task> on 2023-08-29 19:34:41.948544+00:00
[2023-08-29T19:34:44.284+0000] {standard_task_runner.py:57} INFO - Started process 6832 to run task
[2023-08-29T19:34:44.288+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_base_branch_operator', 'python_branch_task', 'manual__2023-08-29T19:34:41.948544+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/dags_base_branch_operator.py', '--cfg-path', '/tmp/tmp225bphct']
[2023-08-29T19:34:44.291+0000] {standard_task_runner.py:85} INFO - Job 149: Subtask python_branch_task
[2023-08-29T19:34:44.360+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_base_branch_operator/run_id=manual__2023-08-29T19:34:41.948544+00:00/task_id=python_branch_task permission to 509
[2023-08-29T19:34:44.361+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_base_branch_operator/run_id=manual__2023-08-29T19:34:41.948544+00:00/task_id=python_branch_task permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_base_branch_operator/run_id=manual__2023-08-29T19:34:41.948544+00:00/task_id=python_branch_task'
[2023-08-29T19:34:44.363+0000] {task_command.py:410} INFO - Running <TaskInstance: dags_base_branch_operator.python_branch_task manual__2023-08-29T19:34:41.948544+00:00 [running]> on host 07fcf706bef2
[2023-08-29T19:34:44.483+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dags_base_branch_operator' AIRFLOW_CTX_TASK_ID='python_branch_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T19:34:41.948544+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-29T19:34:41.948544+00:00'
[2023-08-29T19:34:44.485+0000] {logging_mixin.py:150} INFO - {'conf': <***.configuration.AirflowConfigParser object at 0x7f6d758cbe90>, 'dag': <DAG: dags_base_branch_operator>, 'dag_run': <DagRun dags_base_branch_operator @ 2023-08-29 19:34:41.948544+00:00: manual__2023-08-29T19:34:41.948544+00:00, state:running, queued_at: 2023-08-29 19:34:41.964581+00:00. externally triggered: True>, 'data_interval_end': DateTime(2023, 8, 29, 19, 34, 41, 948544, tzinfo=Timezone('UTC')), 'data_interval_start': DateTime(2023, 8, 29, 19, 34, 41, 948544, tzinfo=Timezone('UTC')), 'ds': '2023-08-29', 'ds_nodash': '20230829', 'execution_date': DateTime(2023, 8, 29, 19, 34, 41, 948544, tzinfo=Timezone('UTC')), 'expanded_ti_count': None, 'inlets': [], 'logical_date': DateTime(2023, 8, 29, 19, 34, 41, 948544, tzinfo=Timezone('UTC')), 'macros': <module '***.macros' from '/home/***/.local/lib/python3.7/site-packages/***/macros/__init__.py'>, 'next_ds': '2023-08-29', 'next_ds_nodash': '20230829', 'next_execution_date': DateTime(2023, 8, 29, 19, 34, 41, 948544, tzinfo=Timezone('UTC')), 'outlets': [], 'params': {}, 'prev_data_interval_start_success': None, 'prev_data_interval_end_success': None, 'prev_ds': '2023-08-29', 'prev_ds_nodash': '20230829', 'prev_execution_date': DateTime(2023, 8, 29, 19, 34, 41, 948544, tzinfo=Timezone('UTC')), 'prev_execution_date_success': None, 'prev_start_date_success': None, 'run_id': 'manual__2023-08-29T19:34:41.948544+00:00', 'task': <Task(CustomBranchOperator): python_branch_task>, 'task_instance': <TaskInstance: dags_base_branch_operator.python_branch_task manual__2023-08-29T19:34:41.948544+00:00 [running]>, 'task_instance_key_str': 'dags_base_branch_operator__python_branch_task__20230829', 'test_mode': False, 'ti': <TaskInstance: dags_base_branch_operator.python_branch_task manual__2023-08-29T19:34:41.948544+00:00 [running]>, 'tomorrow_ds': '2023-08-30', 'tomorrow_ds_nodash': '20230830', 'triggering_dataset_events': <Proxy at 0x7f6d573a34b0 with factory <function TaskInstance.get_template_context.<locals>.get_triggering_events at 0x7f6d5738def0>>, 'ts': '2023-08-29T19:34:41.948544+00:00', 'ts_nodash': '20230829T193441', 'ts_nodash_with_tz': '20230829T193441.948544+0000', 'var': {'json': None, 'value': None}, 'conn': None, 'yesterday_ds': '2023-08-28', 'yesterday_ds_nodash': '20230828'}
[2023-08-29T19:34:44.485+0000] {skipmixin.py:164} INFO - Following branch ['task_b', 'taks_c']
[2023-08-29T19:34:44.493+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/branch.py", line 55, in execute
    self.skip_all_except(context["ti"], branches_to_execute)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/skipmixin.py", line 199, in skip_all_except
    "'branch_task_ids' must contain only valid task_ids. "
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'taks_c'}.
[2023-08-29T19:34:44.500+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dags_base_branch_operator, task_id=python_branch_task, execution_date=20230829T193441, start_date=20230829T193444, end_date=20230829T193444
[2023-08-29T19:34:44.536+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 149 for task python_branch_task ('branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'taks_c'}.; 6832)
[2023-08-29T19:34:44.581+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-29T19:34:44.600+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
