[2023-08-18T23:03:24.819+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_select_dog/run_id=manual__2023-08-18T23:03:21.609826+00:00/task_id=t1_dachshund permission to 509
[2023-08-18T23:03:24.820+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_select_dog/run_id=manual__2023-08-18T23:03:21.609826+00:00/task_id=t1_dachshund permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_select_dog/run_id=manual__2023-08-18T23:03:21.609826+00:00/task_id=t1_dachshund'
[2023-08-18T23:03:25.134+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_select_dog/run_id=manual__2023-08-18T23:03:21.609826+00:00/task_id=t1_dachshund permission to 509
[2023-08-18T23:03:25.145+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_select_dog/run_id=manual__2023-08-18T23:03:21.609826+00:00/task_id=t1_dachshund permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_select_dog/run_id=manual__2023-08-18T23:03:21.609826+00:00/task_id=t1_dachshund'
[2023-08-18T23:03:25.208+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_bash_select_dog.t1_dachshund manual__2023-08-18T23:03:21.609826+00:00 [queued]>
[2023-08-18T23:03:25.217+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_bash_select_dog.t1_dachshund manual__2023-08-18T23:03:21.609826+00:00 [queued]>
[2023-08-18T23:03:25.218+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-18T23:03:25.345+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): t1_dachshund> on 2023-08-18 23:03:21.609826+00:00
[2023-08-18T23:03:25.361+0000] {standard_task_runner.py:57} INFO - Started process 227 to run task
[2023-08-18T23:03:25.381+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_bash_select_dog', 't1_dachshund', 'manual__2023-08-18T23:03:21.609826+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dags_bash_select_dog.py', '--cfg-path', '/tmp/tmp9irjj3di']
[2023-08-18T23:03:25.392+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask t1_dachshund
[2023-08-18T23:03:25.640+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_select_dog/run_id=manual__2023-08-18T23:03:21.609826+00:00/task_id=t1_dachshund permission to 509
[2023-08-18T23:03:25.643+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_select_dog/run_id=manual__2023-08-18T23:03:21.609826+00:00/task_id=t1_dachshund permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_select_dog/run_id=manual__2023-08-18T23:03:21.609826+00:00/task_id=t1_dachshund'
[2023-08-18T23:03:25.655+0000] {task_command.py:410} INFO - Running <TaskInstance: dags_bash_select_dog.t1_dachshund manual__2023-08-18T23:03:21.609826+00:00 [running]> on host 7ff4ca19a8ff
[2023-08-18T23:03:25.983+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dags_bash_select_dog' AIRFLOW_CTX_TASK_ID='t1_dachshund' AIRFLOW_CTX_EXECUTION_DATE='2023-08-18T23:03:21.609826+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-18T23:03:21.609826+00:00'
[2023-08-18T23:03:25.987+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-18T23:03:25.988+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '/plugins/shell/select_dog.sh DACHSHUND']
[2023-08-18T23:03:26.003+0000] {subprocess.py:86} INFO - Output:
[2023-08-18T23:03:26.006+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /plugins/shell/select_dog.sh: No such file or directory
[2023-08-18T23:03:26.006+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-08-18T23:03:26.023+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-08-18T23:03:26.029+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dags_bash_select_dog, task_id=t1_dachshund, execution_date=20230818T230321, start_date=20230818T230325, end_date=20230818T230326
[2023-08-18T23:03:26.072+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 13 for task t1_dachshund (Bash command failed. The command returned a non-zero exit code 127.; 227)
[2023-08-18T23:03:26.113+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-18T23:03:26.146+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
